# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sjLr112q85QQIWxgT6Yq2UQLRDr2r9hn
"""

# Calculadora
# Recebe dois números do usuário
num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))

# Mostra opções de operação
print("Escolha a operação:")
print("1 - Adição (+)")
print("2 - Subtração (-)")
print("3 - Multiplicação (*)")
print("4 - Divisão (/)")

operacao = input("Digite o número da operação desejada: ")

# Executa a operação escolhida
if operacao == "1":
    print("Resultado:", num1 + num2)
elif operacao == "2":
    print("Resultado:", num1 - num2)
elif operacao == "3":
    print("Resultado:", num1 * num2)
elif operacao == "4":
    if num2 != 0:
        print("Resultado:", num1 / num2)
    else:
        print("Erro: divisão por zero não é permitida.")
else:
    print("Opção inválida.")